### ISSUE TITLE
500 Error When Heading to /ask

### ISSUE THREAD

**Issue by Vorrto** [slavingia/askmybook#6]
Hiya,

Not my usual area of extpertise but the demo was so impressive I had to give it a go.

I got everything up and running however I can't get any answers out of it, when I sumbit the request I get a 500 error and visiting the /ask page does the same.

Any suggestions, or where I can look for app based debug logs?

**Comment by slavingia** [comment]
Turn DEBUG to True and ask a question, then see what the server log or browser says

**Comment by johnfewell** [comment]
@Vorrto For me, the issue was the Resemble AI audio, which I am not interested in, so I removed it from line 185 of `views.py`:  
` question = Question(question=question_asked, answer=answer, context=context, audio_src_url=response['item']['audio_src'])` => `question = Question(question=question_asked, answer=answer, context=context)`

**Comment by Vorrto** [comment]
Thanks @johnfewell for the suggestion, unfortunately that doesn't appear to be the issue for me. My error looks like this:
`11:05:24 web.1   |  Quit the server with CTRL-BREAK.
11:05:56 web.1   |  [09/Jan/2023 11:05:56] "GET / HTTP/1.1" 200 8235
11:05:56 web.1   |  [09/Jan/2023 11:05:56] "GET /static/book.png HTTP/1.1" 200 222288
11:05:56 web.1   |  [09/Jan/2023 11:05:56] "GET /static/favicon.svg HTTP/1.1" 200 14027
11:06:01 web.1   |  ===
11:06:02 web.1   |  Internal Server Error: /ask
11:06:02 web.1   |  Traceback (most recent call last):
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
11:06:02 web.1   |      response = get_response(request)
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
11:06:02 web.1   |      response = wrapped_callback(request, *callback_args, **callback_kwargs)
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
11:06:02 web.1   |      return view_func(*args, **kwargs)
11:06:02 web.1   |    File "C:\Users\chris\Documents\GitHub\askmybook\hello\views.py", line 169, in ask
11:06:02 web.1   |      answer, context = answer_query_with_context(question_asked, df, document_embeddings)
11:06:02 web.1   |    File "C:\Users\chris\Documents\GitHub\askmybook\hello\views.py", line 139, in answer_query_with_context
11:06:02 web.1   |      print("===\n", prompt)
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\colorama\ansitowin32.py", line 47, in write
11:06:02 web.1   |      self.__convertor.write(text)
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\colorama\ansitowin32.py", line 177, in write
11:06:02 web.1   |      self.write_and_convert(text)
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
11:06:02 web.1   |      self.write_plain_text(text, cursor, len(text))
11:06:02 web.1   |    File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
11:06:02 web.1   |      self.wrapped.write(text[start:end])
11:06:02 web.1   |    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
11:06:02 web.1   |      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
11:06:02 web.1   |  UnicodeEncodeError: 'charmap' codec can't encode character '\ufb00' in position 1080: character maps to <undefined>
11:06:02 web.1   |  [09/Jan/2023 11:06:02] "POST /ask HTTP/1.1" 500 141378`

Not sure if @slavingia has any tips, I'm a total noob so don't feel like you have to babysit me if you have better things to do!

**Comment by Vorrto** [comment]
Im an idiot.

**Comment by LogarithmicJones** [comment]
How did you fix it?

**Comment by slavingia** [comment]
My guess is that Resemble's API needs to be removed since the sync function needs to be turned on per-account.

**Comment by cook451** [comment]
Could swap in Elevenlabs for voice

**Comment by slavingia** [comment]
Removed voice, so this shouldn’t be an issue anymore
